foa_cron_index:
  path: /
  defaults: { _controller: 'FOACronBundle:Dashboard:index' }

foa_cron_edit:
  path: /{id}/edit
  defaults: { _controller: 'FOACronBundle:Dashboard:edit' }

foa_cron_add:
  path: /add
  defaults: { _controller: 'FOACronBundle:Dashboard:add' }
  methods: [POST]

foa_cron_wakeup:
  path: /{id}/wakeup
  defaults: { _controller: 'FOACronBundle:Dashboard:wakeup' }

foa_cron_suspend:
  path: /{id}/suspend
  defaults: { _controller: 'FOACronBundle:Dashboard:suspend' }

foa_cron_remove:
  path: /{id}/remove
  defaults: { _controller: 'FOACronBundle:Dashboard:remove' }

foa_cron_file:
  path: /{id}/file/{type}
  defaults: { _controller: 'FOACronBundle:Log:file' }
  requirements:
      type: log|error

foa_rest_cron_list:
  path: /rest/cron/
  defaults: { _controller: 'FOACronBundle:Rest\Cron:index' }

