language: php

php:
  - 7.1

matrix:
  allow_failures:
    - php: hhvm

git:
  depth: 10

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"

install:
  - composer --prefer-dist --no-interaction install

script:
  - ./vendor/bin/php-cs-fixer --dry-run -v fix . --rules=@PSR2
  - ./vendor/bin/phpunit tests
